#+TITLE: Algoritmo del filtro
#+AUTHOR: A. Riedinger
#+PROPERTY: header-args :tangle stm/main.c

* ÍNDICE :toc:
- [[#about][ABOUT]]
  - [[#licencia][LICENCIA]]
- [[#setup][SETUP]]
  - [[#clock][CLOCK]]
  - [[#librerias][LIBRERIAS]]
  - [[#definición-variables][DEFINICIÓN VARIABLES]]
  - [[#definición-funciones][DEFINICIÓN FUNCIONES]]
- [[#main][MAIN]]

* ABOUT

Aquí se desarrolla el algoritmo que representa el filtro.

El programa se crea y debugea con el software AtollicTRUEStudio; y la edición del misma se realiza en Doom Emac's.

El proyecto está creado, editado y probado en la placa STM32F429ZI; en caso de utilizar otra placa STM32 (inclusive STM32F4) se debería crear un proyecto en blanco para dicha placa y configurar el clock de manera que iguale al de este proyecto.

** LICENCIA

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

+ The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
+ THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

* SETUP

Aquí se realizan los cambios a los archivos antes de comenzar a configurar el programa. En caso de empezar un archivo en blanco, esto es lo primero que se debería hacer antes de editar.

** CLOCK

Antes de comenzar a editar el programa, es muy importante configurar el clock del sistema para que el mismo trabaje a una frecuencia de XXXX.

Para otras placas, ST ofrece programas que generar el código mediante una interfaz gráfica. Para la placa de este proyecto, se editarán los siguientes archivos:

+ src/system_stm32f4xx.c
+ Libraries/Device/ST/STM32F4xx/Include/stm32f4xx.h

*** system_stm32f4xx.c

Para configurar este archivo, dirigirse a la línea XXX y modificar ...

*** stm32f4xx.h

Este archivo se encuentra en la dirección ....
** LIBRERIAS

Aquí se incluyen las librerías a utilizar para la compilación del programa.

Actualmente, solo se utiliza la librería estándar de C:

#+begin_src C
#include "stm32f4xx.h"
#+end_src

** DEFINICIÓN VARIABLES
** DEFINICIÓN FUNCIONES

* MAIN

#+begin_src C
int main(void)
{
  int i = 0;

  while (1)
  {
	i++;
  }
}
#+end_src
